import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar'
import Footer from '@/components/footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-screen justify-between'>
          <header className='h-20'>
            <Navbar/>
          </header>
          <div className='mb-auto h-10'>
            {children}
          </div>
          <footer className='bottom'>
            <Footer/>
          </footer>
        </div>
      </body>
    </html>
  )
}
